#!/bin/bash

#Charles Wyatt
#cs2750
#10/02/2017

declare -i num;
if [ -z "$1" ]
  then
    num=20
else
  num=$1
fi
for ((n=1;n<=num;n++))
{
    if (( $n % 3 == 0 ))
     then
       echo "Fizz"
    elif (( $n % 5 == 0 ))
     then
       echo "Buzz"
     else
     echo "${n}"
    fi
}
